- hosts: local
  connection: local
  gather_facts: False
  vars_files:
    - "{{ aws_access_secret_keys }}"
  roles:
    - { role: selenium-hub }

- hosts: local
  connection: local
  gather_facts: False
  vars_files:
    - "{{ aws_access_secret_keys }}"  
  roles:
    - { role: selenium-chrome-node }

- hosts: local
  connection: local
  gather_facts: False
  vars_files:
    - "{{ aws_access_secret_keys }}"  
  roles:
    - { role: selenium-firefox-node }
    