version: 2
jobs:
  master_build:
    machine: true

    steps:
      - run: echo "Master branch..."

  circleci_demo_build:
    docker:
      - image: circleci/python:3.6-node

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r code/circleci-demo/app/requirements.txt
        
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            cd code/circleci-demo
            mkdir test-reports
            python -m pytest --junitxml="test-reports/pytest.junit.xml"
            python -m pylint --rcfile=.pylintrc --output-format=parseable app >> test-reports/pylint.out

      - store_test_results:
          path: code/circleci-demo/test-reports

      - store_artifacts:
          path: code/circleci-demo/test-reports

      - run: echo "CircleCI demo branch..."

  docker_build:
    docker:
      - image: docker:18.03.01-git

    working_directory: /app

    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build image
          command: |
            cd code/circleci-demo/app
            docker build -t docker:latest .


workflows:
  version: 2
  master:
    jobs:
      - master_build:
          filters:
            branches:
              only: master
              
  circleci_demo:
    jobs:
      - circleci_demo_build:
          filters:
            branches:
              only: circleci-demo

  docker:
    jobs:
      - docker_build:
          filters:
            branches:
              only: docker
