version: 2
jobs:
  master_build:
    machine: true

    steps:
      - run: echo "Master branch..."

  circleci_demo_build:
    docker:
      - image: circleci/python:latest-node-browsers

    steps:
      - checkout
      - run: echo "CircleCI demo branch..."

workflows:
  version: 2
  master:
    jobs:
      - master_build:
          filters:
            branches:
              only: master

  circleci_demo:
    jobs:
      - circleci_demo_build:
          filters:
            branches:
              only: circleci-demo

