---
########################################################
# Set up Logstash
########################################################

- name: Install logstash
  yum: 
    name: logstash
    state: latest 
    update_cache: yes

- name: Create logstash config
  template:
    src: logstash.config.j2
    dest: /etc/logstash/conf.d/logstash.yml

- name: Force systemd to reread configs
  systemd: daemon_reload=yes

- name: Enable logstash.service
  systemd:
    name: logstash.service
    enabled: yes

- name: Start logstash.service
  systemd: 
    name: logstash.service
    state: restarted
