---
# tasks file for roles/selenium-chrome-node

- name: Launch Selenium Chrome Node EC2 Instance
  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    count: "{{ selenium_chrome_node_count }}"
    group: "{{ security_group }}"
    instance_type: "{{ selenium_chrome_node_instance_type }}"
    image: "{{ selenium_chrome_node_image }}"
    keypair: "{{ keypair }}"
    region: "{{ region }}"    
    wait: true
  register: ec2

- name: Add Selenium Chrome Node Instance to the hosts file
  add_host:
    name: "{{ item.public_ip }}"
    groups: selenium_chrome_nodes
  with_items: "{{ ec2.instances }}"

- name: Add a tag to Selenium Chrome Node EC2 Instance
  ec2_tag:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    resource: "{{ item.id }}"
    region: "{{ region }}"
    state: "present"
  with_items: "{{ ec2.instances }}"
  args:
    tags:
      Type: selenium_chrome_node

- name: Wait for SSH to be ready
  wait_for:
    host: "{{ item.public_ip }}"
    port: 22
    state: started
  with_items: "{{ ec2.instances }}"
